### PR TITLE
Example

### PR DESCRIPTION
**Pull request by marcofranssen**
- [x] Add workflow for example folder
- [x] Include terraform validate in workflow
- [x] Add k8s deployment spire
- [x] Add k8s deployment vault
- [x] Add `spiffe-vault` deployment on k8s
- [x] Add cosign container utilizing `spiffe-vault` to grab signing key from vault https://console.cloud.google.com/gcr/images/projectsigstore/global/cosign
- [x] Add example to retrieve/store a secret in vault utilizing `spiffe-vault`

### CODE REVIEW

**Review by Brend-Smits — COMMENTED** [review]
Hey @marcofranssen,
I was able to get everything working well on my Macbook. 
Since some images are not available yet, I built them locally. Aside from that, I was unable to execute the very last command to cosign the image. I don't think cosign is installed in the container.

Referring to this command: ```$ cosign sign -key hashivault://cosign philipssoftware/spiffe-vault:latest```

Great work, really clear instructions!

**Comment by marcofranssen** [comment]
> Hey @marcofranssen, I was able to get everything working well on my Macbook. Since some images are not available yet, I built them locally. Aside from that, I was unable to execute the very last command to cosign the image. I don't think cosign is installed in the container.
> 
> Referring to this command: `$ cosign sign -key hashivault://cosign philipssoftware/spiffe-vault:latest`
> 
> Great work, really clear instructions!

Correct. Cosign is not in the image. Will work out the example a bit further to also have the cosign binary in a deployment.

**Review by Brend-Smits — APPROVED** [review]
Nice work!!!

**Review by gjkamstra — APPROVED** [review]
Approved on behalf of @Brend-Smits , since he is not a code owner yet

**Pull request merged**
